global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: []
scrape_configs:
- job_name: energeia
  honor_timestamps: true
  scrape_interval: 15s
  metrics_path: /energeia-generic-fo-services/metrics
  scheme: http
  static_configs:
  - targets:
    - 192.168.0.100:9086
- job_name: life-robot
  honor_timestamps: true
  scrape_interval: 15s
  metrics_path: /energeia-life-robot/metrics
  scheme: http
  static_configs:
  - targets:
    - 192.168.0.100:9085
- job_name: non-life-robot
  honor_timestamps: true
  scrape_interval: 15s
  metrics_path: /energeia-robot/metrics
  scheme: http
  static_configs:
  - targets:
    - 192.168.0.100:9084
- job_name: ufk
  honor_timestamps: true
  scrape_interval: 15s
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
  - targets:
    - 192.168.0.100:9010