version: "3"
services:
  postgres:
    #image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: postgres
    #volumes:
      #- ./init.sql:/docker-entrypoint-initdb.d
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - database.env
    restart: unless-stopped

