CREATE DATABASE product;
GRANT ALL PRIVILEGES ON DATABASE product TO postgres;
CREATE DATABASE customer;
GRANT ALL PRIVILEGES ON DATABASE customer TO postgres;
CREATE DATABASE payment;
GRANT ALL PRIVILEGES ON DATABASE payment TO postgres;
CREATE DATABASE policy;
GRANT ALL PRIVILEGES ON DATABASE policy TO postgres;
